### ISSUE TITLE
mysterious dp lib?

### ISSUE THREAD

**Issue by randompersonperson** [R2D2FISH/glados-tts#20]
when i try and run glados.py, i get this error:
Traceback (most recent call last):
  File "/home/mark/coding/glados-tts/glados.py", line 3, in <module>
    from utils.tools import prepare_text
  File "/home/mark/coding/glados-tts/utils/tools.py", line 3, in <module>
    from utils.text.cleaners import Cleaner
  File "/home/mark/coding/glados-tts/utils/text/cleaners.py", line 9, in <module>
    from dp.phonemizer import Phonemizer
ModuleNotFoundError: No module named 'dp.phonemizer'

i checked on pypi, and dp is actually some project with no description that "Automatically transform recursive functions to dynamic programming". so I'm not sure how this is related. please help.

**Comment by R2D2FISH** [comment]
dp.phonemizer is DeepPhonemizer. It should be automatically installed if you install the dependencies with requirements.txt.
